(define (problem medicalPKS10)
	(:domain medicalPKS10)
	(:objects  i0 i1 i2 i3 i4 i5 i6 i7 i8 i9 i10 - ILLNESS
			   s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 - STAIN
	)
 
    (:init (or (and (K (and (stain s0)
					        (not (dead))
						    (ill i1)
					   )
					 )
					(K (oneof (ill i2) 
					          (ill i3)
							  (ill i4)
							  (ill i5)
							  (ill i6)
							  (ill i7)
							  (ill i8)
							  (ill i9)
							  (ill i10)
						)
					)
				    (DK (ill i2))
					(DK (not (ill i2)))
					(DK (ill i3))
					(DK (not (ill i3)))
					(DK (ill i4))
					(DK (not (ill i4)))
					(DK (ill i5))
					(DK (not (ill i5)))
					(DK (ill i6))
					(DK (not (ill i6)))
					(DK (ill i7))
					(DK (not (ill i7))) 
					(DK (ill i8))
					(DK (not (ill i8)))
					(DK (ill i9))
					(DK (not (ill i9)))
					(DK (ill i10))
					(DK (not (ill i10)))
				)
			    (and (K (and (stain s0)
					         (not (dead))
						     (ill i2)
					    )
					  )
					(K (oneof (ill i1) 
					          (ill i3)
							  (ill i4)
							  (ill i5)
							  (ill i6)
							  (ill i7)
							  (ill i8)
							  (ill i9)
							  (ill i10)
						)
					)
				    (DK (ill i1))
					(DK (not (ill i1)))
					(DK (ill i3))
					(DK (not (ill i3)))
					(DK (ill i4))
					(DK (not (ill i4)))
					(DK (ill i5))
					(DK (not (ill i5)))
					(DK (ill i6))
					(DK (not (ill i6)))
					(DK (ill i7))
					(DK (not (ill i7))) 
					(DK (ill i8))
					(DK (not (ill i8)))
					(DK (ill i9))
					(DK (not (ill i9)))
					(DK (ill i10))
					(DK (not (ill i10)))
				)
					
            )
	)
	
	(:goal (K (and (not (dead))
	               (not (ill i1))
				   (not (ill i2))
				   (not (ill i3))
				   (not (ill i4))
				   (not (ill i5))
				   (not (ill i6))
				   (not (ill i7))
				   (not (ill i8))
				   (not (ill i9))
				   (not (ill i10))
				)
		    )
	)
)

