(define (problem farmer)
	(:domain farmer)
	
	(:init (and (or (K (and (ri) (si)))
		              (K (and (wi) (si)))
		          )
	    	      (K (and (fl)
		                  (or (not(ri)) (and (re) (rl)))
			                (or (not(si)) (and (sa) (sl)))
			                (or (not(wi)) (and (wa) (wl)))
		           ) 
		          )
		          (DK (d))
		          (DK (not (d)))
	      )
	)
	
	(:goal (K (and ( or (not(ri)) (re)) (or(not(ri))(not(rl))) (or(not(si))(sa)) (or(not(si))(not(sl))) (or(not(wi))(wa)) (or(not(wi))(not(wl))) ))
	)
)
