(define (problem cube-cube-d40-g20-corners)
	(:domain cube)
	
	(:init(K (and
				(oneof (x p1) 
				       (x p75) 
			    ) 
				(oneof (y p1) 
				       (y p75) 
		        ) 
				(oneof (z p1)
         			   (z p75) 
		        ) 
		      )
		)
    )
	
	(:goal (K (and (x p38)
	               (y p38)
				   (z p38)
			   )
			)
	)
)
