(define (problem cube-cube-d40-g20-corners)
	(:domain cube)
	(:init(K (and
				(oneof (x p1) 
				       (x p99) 
			    ) 
				(oneof (y p1) 
				       (y p99) 
		        ) 
				(oneof (z p1)
         			   (z p99) 
		        ) 
		      )
		)
    )
	
	(:goal (K (and (x p50)
	               (y p50)
				   (z p50)
			   )
			)
	)
)
